name: hello-world
on: push
jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
    -  name: Check out repository code
      users: actions/checkout@v3

    - name: print hello world
      run: echo "Hello World"